services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=walletDB'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=walletDB'
    ports:
      - '5432:5432'

  app:
    container_name: walletProject
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.username: "walletDB"
      spring.datasource.password: "root"
      spring.datasource.url: "jdbc:postgresql://postgres:5432/walletDB"

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always