app:
    host-url: http://localhost:8080

spring:
    init:
        mode: never
    jpa:
        show-sql: true
        open-in-view: false

        # validate db by model
        hibernate:
            ddl-auto: update

        properties:
            #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
            hibernate:
                format_sql: true
                default_batch_fetch_size: 20
                # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
                jdbc.batch_size: 20
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/walletDB
        username: walletDB
        password: root
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5

    liquibase:
        changeLog: "classpath:db/changelog/db.changelog-master.xml"

    # Jackson Fields Serialization
    jackson:
        visibility:
            field: any
            getter: none
            setter: none
            is-getter: none

    # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
    cache:
        cache-names: users
        caffeine.spec: maximumSize=10000,expireAfterAccess=5m

    sql:
        init:
            mode: always

logging:
    level:
        root: INFO
        com.javarush.jira: INFO
        com.javarush.jira.common.config.MvcConfig: INFO
        org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: INFO